// All 50 US States + DC for state-level service pages

export interface StateData {
  name: string;
  slug: string;
  abbreviation: string;
  capital: string;
  largestCity: string;
  population: string;
  majorCities: string[];
  industries: string[];
  description: string;
}

export const states: StateData[] = [
  { name: "Alabama", slug: "alabama", abbreviation: "AL", capital: "Montgomery", largestCity: "Birmingham", population: "5.0M", majorCities: ["Birmingham", "Montgomery", "Huntsville", "Mobile"], industries: ["Automotive", "Aerospace", "Healthcare"], description: "Alabama offers diverse marketing opportunities from Birmingham's growing tech scene to Mobile's port commerce." },
  { name: "Alaska", slug: "alaska", abbreviation: "AK", capital: "Juneau", largestCity: "Anchorage", population: "733K", majorCities: ["Anchorage", "Fairbanks", "Juneau"], industries: ["Oil & Gas", "Tourism", "Fishing"], description: "Alaska's unique market requires specialized staffing for tourism, energy, and remote event activations." },
  { name: "Arizona", slug: "arizona", abbreviation: "AZ", capital: "Phoenix", largestCity: "Phoenix", population: "7.3M", majorCities: ["Phoenix", "Tucson", "Mesa", "Scottsdale", "Chandler"], industries: ["Tech", "Healthcare", "Tourism"], description: "Arizona's booming Phoenix metro and resort destinations offer year-round activation opportunities." },
  { name: "Arkansas", slug: "arkansas", abbreviation: "AR", capital: "Little Rock", largestCity: "Little Rock", population: "3.0M", majorCities: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale"], industries: ["Retail", "Agriculture", "Manufacturing"], description: "Home to Walmart HQ, Arkansas offers unique retail and corporate event staffing opportunities." },
  { name: "California", slug: "california", abbreviation: "CA", capital: "Sacramento", largestCity: "Los Angeles", population: "39.5M", majorCities: ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento"], industries: ["Tech", "Entertainment", "Agriculture"], description: "California is America's largest market with endless opportunities from Silicon Valley tech to Hollywood entertainment." },
  { name: "Colorado", slug: "colorado", abbreviation: "CO", capital: "Denver", largestCity: "Denver", population: "5.8M", majorCities: ["Denver", "Colorado Springs", "Aurora", "Boulder", "Fort Collins"], industries: ["Tech", "Aerospace", "Tourism"], description: "Colorado's active lifestyle culture and growing tech scene make it ideal for experiential marketing." },
  { name: "Connecticut", slug: "connecticut", abbreviation: "CT", capital: "Hartford", largestCity: "Bridgeport", population: "3.6M", majorCities: ["Bridgeport", "New Haven", "Hartford", "Stamford"], industries: ["Finance", "Insurance", "Healthcare"], description: "Connecticut bridges NYC and Boston markets with affluent suburban demographics." },
  { name: "Delaware", slug: "delaware", abbreviation: "DE", capital: "Dover", largestCity: "Wilmington", population: "990K", majorCities: ["Wilmington", "Dover", "Newark"], industries: ["Finance", "Chemicals", "Healthcare"], description: "Delaware's corporate-friendly environment hosts major financial and pharmaceutical companies." },
  { name: "Florida", slug: "florida", abbreviation: "FL", capital: "Tallahassee", largestCity: "Jacksonville", population: "22.2M", majorCities: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale"], industries: ["Tourism", "Healthcare", "Finance"], description: "Florida's tourism industry and diverse population create year-round activation opportunities." },
  { name: "Georgia", slug: "georgia", abbreviation: "GA", capital: "Atlanta", largestCity: "Atlanta", population: "10.8M", majorCities: ["Atlanta", "Augusta", "Savannah", "Columbus"], industries: ["Film", "Tech", "Logistics"], description: "Atlanta is the South's business hub with growing film industry and major corporate headquarters." },
  { name: "Hawaii", slug: "hawaii", abbreviation: "HI", capital: "Honolulu", largestCity: "Honolulu", population: "1.4M", majorCities: ["Honolulu", "Hilo", "Kailua"], industries: ["Tourism", "Military", "Agriculture"], description: "Hawaii's premium tourism market requires specialized staffing for resort and hospitality activations." },
  { name: "Idaho", slug: "idaho", abbreviation: "ID", capital: "Boise", largestCity: "Boise", population: "1.9M", majorCities: ["Boise", "Meridian", "Nampa", "Idaho Falls"], industries: ["Tech", "Agriculture", "Manufacturing"], description: "Idaho's growing Boise tech scene offers emerging market opportunities." },
  { name: "Illinois", slug: "illinois", abbreviation: "IL", capital: "Springfield", largestCity: "Chicago", population: "12.8M", majorCities: ["Chicago", "Aurora", "Naperville", "Rockford"], industries: ["Finance", "Manufacturing", "Tech"], description: "Chicago anchors the Midwest with world-class conventions, sports, and corporate events." },
  { name: "Indiana", slug: "indiana", abbreviation: "IN", capital: "Indianapolis", largestCity: "Indianapolis", population: "6.8M", majorCities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"], industries: ["Manufacturing", "Healthcare", "Sports"], description: "Indianapolis hosts major sporting events including the Indy 500 and NCAA headquarters." },
  { name: "Iowa", slug: "iowa", abbreviation: "IA", capital: "Des Moines", largestCity: "Des Moines", population: "3.2M", majorCities: ["Des Moines", "Cedar Rapids", "Davenport"], industries: ["Insurance", "Agriculture", "Manufacturing"], description: "Iowa's insurance hub and agricultural roots create unique B2B marketing opportunities." },
  { name: "Kansas", slug: "kansas", abbreviation: "KS", capital: "Topeka", largestCity: "Wichita", population: "2.9M", majorCities: ["Wichita", "Overland Park", "Kansas City", "Topeka"], industries: ["Aviation", "Agriculture", "Energy"], description: "Kansas spans from KC metro sophistication to aviation manufacturing in Wichita." },
  { name: "Kentucky", slug: "kentucky", abbreviation: "KY", capital: "Frankfort", largestCity: "Louisville", population: "4.5M", majorCities: ["Louisville", "Lexington", "Bowling Green"], industries: ["Healthcare", "Manufacturing", "Bourbon"], description: "Kentucky offers Kentucky Derby prestige and bourbon tourism marketing opportunities." },
  { name: "Louisiana", slug: "louisiana", abbreviation: "LA", capital: "Baton Rouge", largestCity: "New Orleans", population: "4.6M", majorCities: ["New Orleans", "Baton Rouge", "Shreveport"], industries: ["Energy", "Tourism", "Shipping"], description: "New Orleans' unique culture creates unmatched experiential marketing opportunities." },
  { name: "Maine", slug: "maine", abbreviation: "ME", capital: "Augusta", largestCity: "Portland", population: "1.4M", majorCities: ["Portland", "Lewiston", "Bangor"], industries: ["Tourism", "Healthcare", "Fishing"], description: "Maine's coastal tourism and craft food scene offer seasonal activation opportunities." },
  { name: "Maryland", slug: "maryland", abbreviation: "MD", capital: "Annapolis", largestCity: "Baltimore", population: "6.2M", majorCities: ["Baltimore", "Columbia", "Silver Spring", "Annapolis"], industries: ["Biotech", "Defense", "Healthcare"], description: "Maryland bridges DC and Baltimore with biotech, government, and healthcare markets." },
  { name: "Massachusetts", slug: "massachusetts", abbreviation: "MA", capital: "Boston", largestCity: "Boston", population: "7.0M", majorCities: ["Boston", "Worcester", "Springfield", "Cambridge"], industries: ["Biotech", "Education", "Finance"], description: "Boston's innovation ecosystem and historic culture create premium marketing opportunities." },
  { name: "Michigan", slug: "michigan", abbreviation: "MI", capital: "Lansing", largestCity: "Detroit", population: "10.0M", majorCities: ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing"], industries: ["Automotive", "Healthcare", "Tech"], description: "Michigan's automotive heritage and Detroit's revival offer diverse activation opportunities." },
  { name: "Minnesota", slug: "minnesota", abbreviation: "MN", capital: "Saint Paul", largestCity: "Minneapolis", population: "5.7M", majorCities: ["Minneapolis", "Saint Paul", "Rochester", "Duluth"], industries: ["Healthcare", "Retail", "Finance"], description: "Minneapolis-St. Paul's corporate headquarters and Mall of America drive retail activations." },
  { name: "Mississippi", slug: "mississippi", abbreviation: "MS", capital: "Jackson", largestCity: "Jackson", population: "3.0M", majorCities: ["Jackson", "Gulfport", "Southaven"], industries: ["Manufacturing", "Agriculture", "Gaming"], description: "Mississippi's Gulf Coast casinos and agricultural sector offer targeted marketing opportunities." },
  { name: "Missouri", slug: "missouri", abbreviation: "MO", capital: "Jefferson City", largestCity: "Kansas City", population: "6.2M", majorCities: ["Kansas City", "St. Louis", "Springfield", "Columbia"], industries: ["Healthcare", "Finance", "Manufacturing"], description: "Missouri spans two major metros - KC and St. Louis - with distinct market characteristics." },
  { name: "Montana", slug: "montana", abbreviation: "MT", capital: "Helena", largestCity: "Billings", population: "1.1M", majorCities: ["Billings", "Missoula", "Great Falls", "Bozeman"], industries: ["Tourism", "Agriculture", "Energy"], description: "Montana's outdoor tourism and growing Bozeman tech scene offer unique opportunities." },
  { name: "Nebraska", slug: "nebraska", abbreviation: "NE", capital: "Lincoln", largestCity: "Omaha", population: "2.0M", majorCities: ["Omaha", "Lincoln", "Bellevue"], industries: ["Finance", "Agriculture", "Insurance"], description: "Omaha's financial sector and Warren Buffett connection create B2B opportunities." },
  { name: "Nevada", slug: "nevada", abbreviation: "NV", capital: "Carson City", largestCity: "Las Vegas", population: "3.1M", majorCities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas"], industries: ["Tourism", "Gaming", "Tech"], description: "Las Vegas is America's event capital with unmatched convention and entertainment opportunities." },
  { name: "New Hampshire", slug: "new-hampshire", abbreviation: "NH", capital: "Concord", largestCity: "Manchester", population: "1.4M", majorCities: ["Manchester", "Nashua", "Concord"], industries: ["Tech", "Healthcare", "Manufacturing"], description: "New Hampshire's tax-friendly environment attracts corporate events and retail activations." },
  { name: "New Jersey", slug: "new-jersey", abbreviation: "NJ", capital: "Trenton", largestCity: "Newark", population: "9.3M", majorCities: ["Newark", "Jersey City", "Paterson", "Elizabeth"], industries: ["Pharma", "Finance", "Logistics"], description: "New Jersey's pharma corridor and NYC proximity create diverse marketing opportunities." },
  { name: "New Mexico", slug: "new-mexico", abbreviation: "NM", capital: "Santa Fe", largestCity: "Albuquerque", population: "2.1M", majorCities: ["Albuquerque", "Las Cruces", "Santa Fe"], industries: ["Government", "Tech", "Tourism"], description: "New Mexico's film industry growth and cultural tourism offer creative activation opportunities." },
  { name: "New York", slug: "new-york", abbreviation: "NY", capital: "Albany", largestCity: "New York City", population: "20.2M", majorCities: ["New York City", "Buffalo", "Rochester", "Albany"], industries: ["Finance", "Media", "Tech"], description: "New York City is the world's marketing capital with unlimited experiential opportunities." },
  { name: "North Carolina", slug: "north-carolina", abbreviation: "NC", capital: "Raleigh", largestCity: "Charlotte", population: "10.4M", majorCities: ["Charlotte", "Raleigh", "Durham", "Greensboro"], industries: ["Banking", "Tech", "Healthcare"], description: "North Carolina's Research Triangle and Charlotte banking hub drive corporate activations." },
  { name: "North Dakota", slug: "north-dakota", abbreviation: "ND", capital: "Bismarck", largestCity: "Fargo", population: "780K", majorCities: ["Fargo", "Bismarck", "Grand Forks"], industries: ["Energy", "Agriculture", "Tech"], description: "North Dakota's energy boom and agricultural sector create targeted B2B opportunities." },
  { name: "Ohio", slug: "ohio", abbreviation: "OH", capital: "Columbus", largestCity: "Columbus", population: "11.8M", majorCities: ["Columbus", "Cleveland", "Cincinnati", "Toledo"], industries: ["Healthcare", "Manufacturing", "Finance"], description: "Ohio's three major metros offer diverse Midwest marketing opportunities." },
  { name: "Oklahoma", slug: "oklahoma", abbreviation: "OK", capital: "Oklahoma City", largestCity: "Oklahoma City", population: "4.0M", majorCities: ["Oklahoma City", "Tulsa", "Norman"], industries: ["Energy", "Aerospace", "Agriculture"], description: "Oklahoma's energy sector and growing OKC metro create emerging market opportunities." },
  { name: "Oregon", slug: "oregon", abbreviation: "OR", capital: "Salem", largestCity: "Portland", population: "4.2M", majorCities: ["Portland", "Salem", "Eugene", "Bend"], industries: ["Tech", "Manufacturing", "Tourism"], description: "Portland's creative culture and outdoor lifestyle create unique experiential opportunities." },
  { name: "Pennsylvania", slug: "pennsylvania", abbreviation: "PA", capital: "Harrisburg", largestCity: "Philadelphia", population: "13.0M", majorCities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie"], industries: ["Healthcare", "Finance", "Manufacturing"], description: "Pennsylvania spans Philadelphia's historic market to Pittsburgh's tech renaissance." },
  { name: "Rhode Island", slug: "rhode-island", abbreviation: "RI", capital: "Providence", largestCity: "Providence", population: "1.1M", majorCities: ["Providence", "Warwick", "Cranston"], industries: ["Healthcare", "Education", "Defense"], description: "Rhode Island's compact market and coastal charm offer targeted activation opportunities." },
  { name: "South Carolina", slug: "south-carolina", abbreviation: "SC", capital: "Columbia", largestCity: "Charleston", population: "5.1M", majorCities: ["Charleston", "Columbia", "Greenville", "Myrtle Beach"], industries: ["Manufacturing", "Tourism", "Automotive"], description: "South Carolina's coastal tourism and manufacturing growth drive diverse activations." },
  { name: "South Dakota", slug: "south-dakota", abbreviation: "SD", capital: "Pierre", largestCity: "Sioux Falls", population: "890K", majorCities: ["Sioux Falls", "Rapid City", "Aberdeen"], industries: ["Finance", "Healthcare", "Tourism"], description: "South Dakota's financial services sector and Mount Rushmore tourism offer niche opportunities." },
  { name: "Tennessee", slug: "tennessee", abbreviation: "TN", capital: "Nashville", largestCity: "Nashville", population: "6.9M", majorCities: ["Nashville", "Memphis", "Knoxville", "Chattanooga"], industries: ["Healthcare", "Music", "Automotive"], description: "Nashville's explosive growth and Memphis music heritage create unmatched event opportunities." },
  { name: "Texas", slug: "texas", abbreviation: "TX", capital: "Austin", largestCity: "Houston", population: "29.1M", majorCities: ["Houston", "Dallas", "San Antonio", "Austin", "Fort Worth"], industries: ["Energy", "Tech", "Healthcare"], description: "Texas is America's second-largest market with diverse opportunities across multiple major metros." },
  { name: "Utah", slug: "utah", abbreviation: "UT", capital: "Salt Lake City", largestCity: "Salt Lake City", population: "3.3M", majorCities: ["Salt Lake City", "West Valley City", "Provo", "Park City"], industries: ["Tech", "Tourism", "Healthcare"], description: "Utah's Silicon Slopes tech boom and outdoor recreation create growing market opportunities." },
  { name: "Vermont", slug: "vermont", abbreviation: "VT", capital: "Montpelier", largestCity: "Burlington", population: "645K", majorCities: ["Burlington", "Essex", "Rutland"], industries: ["Tourism", "Agriculture", "Healthcare"], description: "Vermont's artisan culture and ski tourism offer premium seasonal activations." },
  { name: "Virginia", slug: "virginia", abbreviation: "VA", capital: "Richmond", largestCity: "Virginia Beach", population: "8.6M", majorCities: ["Virginia Beach", "Norfolk", "Richmond", "Arlington"], industries: ["Defense", "Tech", "Government"], description: "Virginia's DC suburbs and Hampton Roads military presence drive government and defense marketing." },
  { name: "Washington", slug: "washington", abbreviation: "WA", capital: "Olympia", largestCity: "Seattle", population: "7.6M", majorCities: ["Seattle", "Spokane", "Tacoma", "Vancouver"], industries: ["Tech", "Aerospace", "Retail"], description: "Seattle's tech giants and coffee culture create innovative experiential marketing opportunities." },
  { name: "West Virginia", slug: "west-virginia", abbreviation: "WV", capital: "Charleston", largestCity: "Charleston", population: "1.8M", majorCities: ["Charleston", "Huntington", "Morgantown"], industries: ["Energy", "Healthcare", "Tourism"], description: "West Virginia's outdoor adventure tourism offers niche activation opportunities." },
  { name: "Wisconsin", slug: "wisconsin", abbreviation: "WI", capital: "Madison", largestCity: "Milwaukee", population: "5.9M", majorCities: ["Milwaukee", "Madison", "Green Bay"], industries: ["Manufacturing", "Healthcare", "Agriculture"], description: "Wisconsin's brewing heritage and passionate sports culture drive unique event activations." },
  { name: "Wyoming", slug: "wyoming", abbreviation: "WY", capital: "Cheyenne", largestCity: "Cheyenne", population: "577K", majorCities: ["Cheyenne", "Casper", "Laramie", "Jackson"], industries: ["Energy", "Tourism", "Agriculture"], description: "Wyoming's Yellowstone tourism and energy sector offer targeted activation opportunities." },
  { name: "District of Columbia", slug: "washington-dc", abbreviation: "DC", capital: "Washington", largestCity: "Washington", population: "689K", majorCities: ["Washington"], industries: ["Government", "Tourism", "Tech"], description: "Washington DC is the nation's political center with unique government, association, and tourism marketing opportunities." }
];

export const stateServices = [
  { slug: "brand-ambassadors", name: "Brand Ambassadors", description: "Professional brand representatives for product launches, retail activations, and consumer engagement campaigns." },
  { slug: "event-staffing", name: "Event Staffing", description: "Experienced staff for conferences, trade shows, corporate events, and special occasions." },
  { slug: "street-teams", name: "Street Teams", description: "High-energy teams for guerrilla marketing, product sampling, and grassroots activations." },
  { slug: "promotional-models", name: "Promotional Models", description: "Attractive, professional models for trade shows, auto shows, and high-profile brand activations." },
  { slug: "experiential-marketing", name: "Experiential Marketing", description: "Full-service experiential campaigns that create memorable brand experiences and drive engagement." },
  { slug: "convention-staffing", name: "Convention Staffing", description: "Trade show and convention specialists for booth management, lead generation, and product demos." },
  { slug: "product-sampling", name: "Product Sampling", description: "Strategic sampling campaigns that drive trial, awareness, and purchase consideration." },
  { slug: "event-management", name: "Event Management", description: "End-to-end event planning and execution services for corporate and consumer events." },
  { slug: "hospitality-staff", name: "Hospitality Staff", description: "Professional hospitality teams for VIP events, corporate functions, and premium brand experiences." }
];

export function getStateBySlug(slug: string): StateData | undefined {
  return states.find(s => s.slug === slug);
}

export function getStateServiceBySlug(slug: string) {
  return stateServices.find(s => s.slug === slug);
}
